; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

monitor_speed = 115200

; Upload settings (IMPORTANT for ESP32-CAM)
upload_speed = 115200

; Libraries
lib_deps =
    adafruit/Adafruit BMP085 Library
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor

; Fix for PSRAM / stability
board_build.partitions = huge_app.csv
board_build.flash_mode = dio

; Optional: more debug info
build_flags =
    -DCORE_DEBUG_LEVEL=1